# POSTTES 7 (TENSORFLOW)

In [1]:
import tensorflow as tf
import numpy as np

# Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
random_tensor.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

# Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [16]:
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
tf.convert_to_tensor(prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [31, 37, 41, 43, 47],
       [53, 59, 61, 67, 71],
       [73, 79, 83, 89, 97]])>

# Tampilkan dimensi dari kedua variable tersebut

In [17]:
random_tensor.shape

TensorShape([5, 5])

Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

PENJUMLAHAN

In [19]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
print(tf.add(random_tensor,prime_tensor))

tf.Tensor(
[[ 1.6761351  3.9913368  5.1402426  8.257397  11.099923 ]
 [13.189833  16.712889  17.25864   24.871876  26.98955  ]
 [29.532698  35.727802  40.219627  43.94073   46.93835  ]
 [50.91575   59.61423   59.54891   66.11307   70.03259  ]
 [73.94832   78.30255   83.53915   88.4703    94.98946  ]], shape=(5, 5), dtype=float32)


PEMBAGIAN

In [27]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
print(tf.divide(random_tensor,prime_tensor))

tf.Tensor(
[[ 2.6710117e-03 -3.4868124e-01 -3.2855296e-01 -4.9933385e-02
   8.6495548e-02]
 [ 6.2352516e-02 -4.4808295e-02  5.3350762e-02 -8.0305278e-02
   6.9557857e-03]
 [ 3.9269436e-02 -4.7498003e-02  4.3069072e-02  2.6512560e-02
   1.7697476e-02]
 [-3.7687927e-02  4.2672469e-03  1.7524315e-02  4.5014694e-03
   3.7210886e-03]
 [ 3.1734267e-04  9.1428328e-03  4.5115938e-03 -1.0739432e-03
   1.4624439e-02]], shape=(5, 5), dtype=float32)


LOGARITMA

In [28]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
print(tf.math.log(random_tensor,prime_tensor))

tf.Tensor(
[[-3.6375911  -0.5112753   0.78527486 -0.34886786         nan]
 [        nan         nan -2.2177489          nan         nan]
 [        nan -1.0908935          nan         nan         nan]
 [        nan  0.15537421         nan  0.19540821 -0.41779348]
 [-1.588368   -2.5325453  -2.6301417          nan         nan]], shape=(5, 5), dtype=float32)


PANGKAT

In [29]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
print(tf.pow(random_tensor,prime_tensor))

tf.Tensor(
[[ 9.66102723e-03  1.87378371e+00  1.49746859e+00 -3.05974829e-11
   1.18807375e-01]
 [-4.66760139e+01 -1.02345221e-04 -6.35636139e+01  4.29921830e-03
  -1.63839281e+05]
 [ 1.31553137e+10  1.60909221e-02 -0.00000000e+00 -4.73134349e+20
   0.00000000e+00]
 [ 5.26591934e-20 -8.33039874e-32  2.75768667e-01  5.51942154e+14
   0.00000000e+00]
 [ 0.00000000e+00 -0.00000000e+00 -1.76782157e-12 -4.32036650e-05
   0.00000000e+00]], shape=(5, 5), dtype=float32)


In [30]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
print(tf.multiply(random_tensor,prime_tensor))

tf.Tensor(
[[  0.44576672   3.23009      8.17774      1.9855111    2.3667278 ]
 [ -2.6687586   29.97019    -11.708298    13.990379   -44.60974   ]
 [ -6.82516    -99.193794    -1.7434397   34.185593   -13.200857  ]
 [-82.21638    -36.744633   -23.708965    77.98874      3.8308885 ]
 [ 36.13413     24.786385    49.64158    136.75969    -83.99319   ]], shape=(5, 5), dtype=float32)


# Tampilkan nilai maksimal dan minimal dari variable random_tensor

NILAI MAKSIMAL

In [ ]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
print("input tensor:",random_tensor.numpy())
max_tensor_1 = tf.argmax(random_tensor, axis=0)
max_tensor_2 = tf.argmax(random_tensor, axis=1)
print("locate the maximum value by column:",max_tensor_1.numpy())
print("locate the maximum value by row:",max_tensor_2.numpy())

input tensor: [[-1.3108554  -1.1593145   0.73543155 -1.5630164  -1.4232419 ]
 [-1.7293437  -0.47802517  1.234133   -0.30225113  0.2919897 ]
 [ 0.99688596 -2.0894635   0.06678373  0.5522131  -1.9784949 ]
 [-1.2640431   0.9884551   0.33365408 -1.7091124  -0.63588405]
 [-0.8078736   0.850547   -1.4636692  -0.83810955  1.3281822 ]]
locate the maximum value by column: [2 3 1 2 4]
locate the maximum value by row: [2 2 0 1 4]


NILAI MINIMAL

In [38]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
print("input tensor:",random_tensor.numpy())
max_tensor_1 = tf.argmin(random_tensor, axis=0)
max_tensor_2 = tf.argmin(random_tensor, axis=1)
print("locate the maximum value by column:",max_tensor_1.numpy())
print("locate the maximum value by row:",max_tensor_2.numpy())

input tensor: [[-0.9568206  -0.3519852   0.39326212 -0.2814874   0.30489728]
 [ 1.000067   -0.7087076  -0.5729673  -0.18705048 -0.20621224]
 [-0.00663627  1.4536982   0.87069196 -0.15616864 -0.04469914]
 [-0.62138456  0.8326373  -1.7155293  -0.18671067 -1.5751405 ]
 [-0.805046    0.14572485 -0.6442465   0.4096017   0.23699413]]
locate the maximum value by column: [0 1 3 0 3]
locate the maximum value by row: [0 1 3 2 0]


# Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [42]:
random_tensor = tf.random.normal([5,5], mean=0., stddev=1.,seed=1)
prime_tensor = [[2,3,5,7,11],
                [13,17,19,23,29],
                [31,37,41,43,47],
                [53,59,61,67,71],
                [73,79,83,89,97]]
print("sizes of the original data:",random_tensor,prime_tensor)
concated_random_tensor = tf.concat([random_tensor,prime_tensor],axis=0)
print("size of the concatenated data:",concated_random_tensor.shape)

sizes of the original data: tf.Tensor(
[[-1.919179    0.01829506  0.7765734  -0.7832411   0.30757543]
 [ 1.1416744   0.1886675   1.5900987   0.00705396  1.0032494 ]
 [ 1.1453512  -1.7364683   0.21526565  0.03201041  1.3139104 ]
 [-0.3118233   0.10879678 -1.2742105  -1.732707   -0.20808774]
 [-1.0841713  -0.24528262 -1.0429802  -0.28368196 -1.0766255 ]], shape=(5, 5), dtype=float32) [[2, 3, 5, 7, 11], [13, 17, 19, 23, 29], [31, 37, 41, 43, 47], [53, 59, 61, 67, 71], [73, 79, 83, 89, 97]]
size of the concatenated data: (10, 5)


In [44]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()

array([[-1.9191790e+00,  1.8295057e-02,  7.7657342e-01, -7.8324109e-01,
         3.0757543e-01,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 1.1416744e+00,  1.8866751e-01,  1.5900987e+00,  7.0539583e-03,
         1.0032494e+00,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 1.1453512e+00, -1.7364683e+00,  2.1526565e-01,  3.2010406e-02,
         1.3139104e+00,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-3.1182331e-01,  1.0879678e-01, -1.2742105e+00, -1.7327070e+00,
        -2.0808774e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         6.7000000e+01,  7.1000000e+01],
       [-1.0841713e+00, -2.4528262e-01, -1.0429802e+00, -2.8368196e-01,
        -1.0766255e+00,  7.3000000e+01,  7.9000000e+01,  8.3000000e+01,
         8.9000000e+01,  9.7000000e+01]], dtype=float32)

In [45]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()

array([[-1.9191790e+00,  1.8295057e-02,  7.7657342e-01, -7.8324109e-01,
         3.0757543e-01],
       [ 1.1416744e+00,  1.8866751e-01,  1.5900987e+00,  7.0539583e-03,
         1.0032494e+00],
       [ 1.1453512e+00, -1.7364683e+00,  2.1526565e-01,  3.2010406e-02,
         1.3139104e+00],
       [-3.1182331e-01,  1.0879678e-01, -1.2742105e+00, -1.7327070e+00,
        -2.0808774e-01],
       [-1.0841713e+00, -2.4528262e-01, -1.0429802e+00, -2.8368196e-01,
        -1.0766255e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01]], dtype=float32)

# Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [47]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[ 0.7765734 ,  0.30757543,  0.01829506, -0.7832411 , -1.919179  ],
       [ 1.5900987 ,  1.1416744 ,  1.0032494 ,  0.1886675 ,  0.00705396],
       [ 1.3139104 ,  1.1453512 ,  0.21526565,  0.03201041, -1.7364683 ],
       [ 0.10879678, -0.20808774, -0.3118233 , -1.2742105 , -1.732707  ],
       [-0.24528262, -0.28368196, -1.0429802 , -1.0766255 , -1.0841713 ]],
      dtype=float32)

In [62]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[2, 4, 1, 3, 0],
       [2, 0, 4, 1, 3],
       [4, 0, 2, 3, 1],
       [1, 4, 0, 2, 3],
       [1, 3, 2, 4, 0]])

In [53]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11,  7,  5,  3,  2],
       [29, 23, 19, 17, 13],
       [47, 43, 41, 37, 31],
       [71, 67, 61, 59, 53],
       [97, 89, 83, 79, 73]])

In [58]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0]])